# Generated by Django 3.0.8 on 2021-05-23 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('rations_available', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diners', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('dishes', models.ManyToManyField(to='menu.Dish')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Table')),
            ],
        ),
    ]
