# Generated by Django 3.2.3 on 2021-05-23 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_table_orders_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='orders_placed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.order'),
        ),
    ]
