# Generated by Django 3.2.3 on 2021-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='orders_placed',
        ),
        migrations.AddField(
            model_name='table',
            name='orders_placed',
            field=models.ManyToManyField(to='menu.Order'),
        ),
    ]
