# Generated by Django 3.2.3 on 2021-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20210523_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='orders_placed',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Order'),
        ),
    ]
