# Generated by Django 3.2.3 on 2021-05-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_table_orders_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='orders_placed',
        ),
    ]
